GetBalance for non-nullified commitments.
EYBlockchain/starlight pull request #236
Opened 2024-03-27 16:55 UTC by kKahina

getBalance return the value of the non-nullified commitments.

2024-04-03 12:11 UTC, SwatiEY requested changes

2024-04-03 12:11 UTC, SwatiEY commented on src/traverse/Scope.ts
we are not using the isPublic key. if it is not used, can you please remove it

2024-04-03 12:11 UTC, SwatiEY commented on src/codeGenerators/orchestration/files/toOrchestration.ts
please remove the unnecessary blank lines

2024-04-03 12:11 UTC, SwatiEY commented on src/boilerplate/orchestration/javascript/nodes/boilerplate-generator.ts
Remove the unnecessary blank lines

2024-04-03 12:11 UTC, SwatiEY commented on src/boilerplate/common/web3.mjs
Please remove the blank lines

2024-04-03 12:11 UTC, SwatiEY commented on src/boilerplate/common/commitment-storage.mjs
Please remove the blank lines

2024-04-04 11:24 UTC, kKahina reviewed
I removed the blank lines

2024-04-04 13:33 UTC, lydiagarms approved these changes

2024-04-04 13:33 UTC, lydiagarms commented on src/boilerplate/common/commitment-storage.mjs
Could you translate the comments to English?

2024-04-04 16:07 UTC, SwatiEY approved these changes

2024-04-04 16:07 UTC, merged