Swati/internal function call
EYBlockchain/starlight pull request #96
Opened 2022-04-20 15:28 UTC by SwatiEY

This partially closes #68 
Modified the Visitors (Circuit, contract and Orchestration) for internal function calls.
Added test contracts as well. 
We check if correct arguments are passed with correct decorators.
If the same state is modified in the internal Function call, we don't import the circuit, we just copy over the expression statements.

2022-04-22 12:22 UTC, MirandaWood requested changes

2022-04-22 12:22 UTC, MirandaWood commented on src/transformers/visitors/toContractVisitor.ts
> +let internalFncName = [];
Same as before, if these could be stored as properties of `state`

2022-04-22 12:22 UTC, MirandaWood commented on src/transformers/visitors/toContractVisitor.ts
> +if(internalFuncInteractsWithSecret){
could you look at the indentation here as well please? Maybe the below lines would be better as a `switch` statement :)

2022-04-22 12:22 UTC, MirandaWood commented on src/transformers/visitors/toOrchestrationVisitor.ts
> +let internalFncName = [];
In state as above :)

2022-04-22 12:22 UTC, MirandaWood commented on src/transformers/visitors/toOrchestrationVisitor.ts
> +})
Could we separate this into a function at the top or maybe a new file? The code is great but lengthy!

2022-04-22 12:22 UTC, MirandaWood commented on src/transformers/visitors/toOrchestrationVisitor.ts
> +      if(path.isInternalFunctionCall()) {
Indentation and smushing (technical term :) ) below where possible would be good please

2022-04-22 12:22 UTC, MirandaWood commented on src/types/solidity-types.ts
> +      return ['name', 'internalFunctionInteractsWithSecret','parameters'];
`internalFunctionInteractsWithSecret` isn't a visitable key btw - these keys are only things that the visitor should look at to find the next node in the tree

2022-05-03 11:51 UTC, MirandaWood commented on src/boilerplate/contract/solidity/raw/FunctionBoilerplateGenerator.ts
> +        ...(newCommitments || newNullifiers ? [`uint256[] calldata proof`] : []),
```suggestion
        ...(newCommitments ? [`uint256[] ${visibility} newCommitments`] : []),
        ...(checkNullifiers ? [`uint256[] ${visibility} checkNullifiers`] : []),
        ...(newCommitments || newNullifiers ? [`uint256[] ${visibility} proof`] : []),
```

We need to keep these changes from master, so the constructor circuits works :)

2022-05-03 12:00 UTC, MirandaWood commented on src/traverse/scope.ts
> +          break;
This may have been one of my changes I forgot about - but if not could you explain why we remove the error here?

2022-05-03 12:12 UTC, MirandaWood commented on test/contracts/InternalFunctionError1.zol
> +// SPDX-License-Identifier: CC0
Could we move any test that results in an error to `error-checks` please?

2022-05-23 05:28 UTC, dwebchapey approved these changes

2022-05-23 08:55 UTC, MirandaWood approved these changes

2022-05-23 11:03 UTC, merged